"""Convert docs/logo/foyer-hd-icon.svg into a filled path for `foyer:shield`.

Home Assistant renders custom icons as filled SVG paths in ``currentColor``;
strokes are not supported. This script outlines the icon's strokes with the same
geometry (stroke width 3.4, round joins and caps) and writes the result to
frontend/src/icons/icon-path.ts. It does not redraw or simplify the icon: if
the SVG changes, run it again.

    pip install shapely
    python scripts/build_sidebar_icon.py
"""

from __future__ import annotations

from pathlib import Path

from shapely.geometry import LineString, Point, Polygon, box
from shapely.geometry.polygon import orient
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "frontend" / "src" / "icons" / "icon-path.ts"
STROKE = 3.4
HALF = STROKE / 2


def cubic(p0, p1, p2, p3, steps=24):
    pts = []
    for i in range(1, steps + 1):
        t = i / steps
        mt = 1 - t
        pts.append(
            (
                mt**3 * p0[0]
                + 3 * mt**2 * t * p1[0]
                + 3 * mt * t**2 * p2[0]
                + t**3 * p3[0],
                mt**3 * p0[1]
                + 3 * mt**2 * t * p1[1]
                + 3 * mt * t**2 * p2[1]
                + t**3 * p3[1],
            )
        )
    return pts


def shield_outline() -> list[tuple[float, float]]:
    # M32 5.5 L55 13.5 V32 C55 44 45 53.5 32 58.5 C19 53.5 9 44 9 32 V13.5 Z
    pts = [(32, 5.5), (55, 13.5), (55, 32)]
    pts += cubic((55, 32), (55, 44), (45, 53.5), (32, 58.5))
    pts += cubic((32, 58.5), (19, 53.5), (9, 44), (9, 32))
    pts += [(9, 13.5)]
    return pts


def build():
    shield = Polygon(shield_outline())
    # A closed stroke is the band between the outline grown and shrunk by half
    # the stroke width, with round joins.
    shield_stroke = shield.buffer(HALF, join_style="round").difference(
        shield.buffer(-HALF, join_style="mitre")
    )
    roof = LineString([(19, 32), (32, 21.5), (45, 32)]).buffer(
        HALF, cap_style="round", join_style="round"
    )
    door = unary_union([box(28.5, 45.5, 35.5, 52.5), Point(32, 45.5).buffer(3.5)])
    return unary_union([shield_stroke, roof, door])


def ring_to_d(coords) -> str:
    pts = list(coords)[:-1]
    head, *rest = pts
    parts = [f"M{head[0]:.2f} {head[1]:.2f}"]
    parts += [f"L{x:.2f} {y:.2f}" for x, y in rest]
    return "".join(parts) + "Z"


def to_path(geom) -> str:
    polys = getattr(geom, "geoms", [geom])
    d = []
    for raw in polys:
        # HA's <ha-svg-icon> fills with the default nonzero rule, so holes must
        # wind opposite to their exterior to stay holes.
        poly = orient(raw, sign=1.0)
        d.append(ring_to_d(poly.exterior.coords))
        d.extend(ring_to_d(ring.coords) for ring in poly.interiors)
    return "".join(d)


def main() -> None:
    d = to_path(build())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_sidebar_icon.py from\n"
        "// docs/logo/foyer-hd-icon.svg. Do not edit by hand.\n"
        "// The path is in the icon's 64-unit grid.\n"
        'export const ICON_VIEWBOX = "0 0 64 64";\n'
        f'export const ICON_PATH =\n  "{d}";\n',
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(d)} chars)")


if __name__ == "__main__":
    main()
